_ad1 = "leroidu45"
_ad2 = "CoolSupX_0"
_ad3 = "nil"
_ad4 = "nil"
_ad5 = "nil"

_astra = "SPDM_Astra | flipper_zero | Dev,Scripter,Gui Maker"
_heclom = "heclom  |  ?????  |  Support,Helper,Gui Helper,Friend,Admin"
_sigma = "sigma  |  giga_Sigma200  |  Friend,Admin,Helper"


_scmsg = "Succes"
_betamsg = "Your Launching Beta Version Of ZerarchiHub, Welcome"

_blc = "nil"
_blc1 = "nil"
_blc2 = "nil"
_blc3 = "nil"
_blc4 = "nil"
_blc5 = "nil"
_blc6 = "nil"
_blc7 = "nil"
_blc8 = "nil"
_blc9 = "nil"
_blc01 = "nil"
